language: node_js
sudo: false
node_js:
  - '8'
  - '9'
  - 'node'

script:
  - npm test -- --no-watch --no-progress --code-coverage --browsers=ChromeHeadlessCI

after_success:
  - cat ./coverage/angular2-jsonapi/lcov.info | ./node_modules/coveralls/bin/coveralls.js
